version: "3.8"
services:
  godaddy-ddns:
    image: linuxshots/godaddy-ddns
    restart: always
    env_file:
      - .env
    command: sh -c "while :; do sleep 3600; done" # Adjust the sleep interval as needed
networks: {}
