version: "3.7"
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - C:\dev\docker-stuff_config\Caddy\Caddyfile:/etc/caddy/Caddyfile
      - ./Caddyfile:/etc/caddy/Caddyfile
      - C:\dev\docker-stuff_config\Caddy\data:/data
      - C:\dev\docker-stuff_config\Caddy\config:/config
